// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIhyXWgxuzfWc8EYhDO9owHv-TlkURVXE',
    appId: '1:367234072809:web:c99ce9de09eb28d8573078',
    messagingSenderId: '367234072809',
    projectId: 'fusionnews-41a5c',
    authDomain: 'fusionnews-41a5c.firebaseapp.com',
    storageBucket: 'fusionnews-41a5c.appspot.com',
    measurementId: 'G-NMPTCSFRM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-4osv3v47iuUlWX9Bu-DCsP1w79LqAA',
    appId: '1:367234072809:android:1334d7170efc6723573078',
    messagingSenderId: '367234072809',
    projectId: 'fusionnews-41a5c',
    storageBucket: 'fusionnews-41a5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVlHRaIMZnNNfzIWjjeC1lUZxxfiP-WE',
    appId: '1:367234072809:ios:d65e86c2a45ccb65573078',
    messagingSenderId: '367234072809',
    projectId: 'fusionnews-41a5c',
    storageBucket: 'fusionnews-41a5c.appspot.com',
    iosBundleId: 'com.example.fusionNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVlHRaIMZnNNfzIWjjeC1lUZxxfiP-WE',
    appId: '1:367234072809:ios:45798d6e4005a4f9573078',
    messagingSenderId: '367234072809',
    projectId: 'fusionnews-41a5c',
    storageBucket: 'fusionnews-41a5c.appspot.com',
    iosBundleId: 'com.example.fusionNews.RunnerTests',
  );
}
